name: Python package

on: [push]

jobs:
  build:

steps:
- uses: actions/checkout@v4
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
- name: Test with Unit 2 python code.py
  run: |
  result = x+y:
    print(x,"+",y,"=",result)

n1 = int(input("Enter first vairiable:"))
n2 = int(input("Enter second variable:"))

add(n1,n2)
    



